
spring:
  application:
    name: animals-api
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:animalsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      username: sa
      password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 60000
            readTimeout: 60000
            loggerLevel: basic

client:
  cat:
    baseUrl: ${CAT_BASE_URL:https://api.thecatapi.com/v1}
    apiKey: ${CAT_API_KEY:live_Bxdwieb8UDcUM5o8rCZYdWbMtikeLoGP8UuGJW4i0Lads9rgibYb6D2z4XUaBaVy}
  dog:
    baseUrl: ${DOG_BASE_URL:https://api.thedogapi.com/v1}
    apiKey: ${DOG_API_KEY:live_OGOWRqSOa7JbxI7dNJtOwkTLARsyTrH2kejXYguF4Cl706Qle4X3N2pcti3oIxBJ}
